version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Run Tests
          command: yarn run test
      - persist_to_workspace:
          root: .
          paths:
            - .nyc_output

  coverage:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Check Coverage
          command: npx nyc report --check-coverage --temp-directory .nyc_output
  
  eslint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Run ESLint
          command: yarn run eslint . --max-warnings 0

workflows:
  tictactoeCI:
    jobs:
      - eslint
      - test:
          version: '16.10'
          pkg-manager: yarn
          requires:
            - eslint
      - coverage:
          requires:
            - test